### ISSUE TITLE
[FE] factoryを叩く画面

### ISSUE THREAD

**Issue by neila** [ETH-Tokyo/gas-less-token#6]
最初の最初にownerがfactoryを作る際の画面。

**Comment by kentatakase** [comment]
Figma
https://www.figma.com/file/xaZP73GmNzqe2inyCebuli/ETH-global-WF?node-id=0-1&t=rIh2XkTtAQRcbNmH-0
本当にざっくりでピクセルとか合わせてないです

factoryを叩くために必要なinput情報が定まってなく、施行中だったりします。

**Comment by eri2490** [comment]
@neila これ未着手できたら進めます。着手中だったらhttps://github.com/ETH-Tokyo/gas-less-token/issues/9やります

**Comment by neila** [comment]
未着手です！お願いします！
